### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/integration_alephalpha#2]
* Maybe the reference provider should only be registered if an API key is defined
* Or we should find a way to show a meaningful error when using the gptfreeprompt smart picker provider
* The `src/bootstrap.js` file is not used and can be deleted
* The `/models` route is not used. Did you plan to make it possible to set the default used model in the admin settings? You could retrieve the list of available models as soon as an API key is defined and let the admin choose one which would be stored with the `completion_model` app config key.
* The API base URL (used in service::request) could be a constant as well
* Saving the API key on each `input` event is a bit too much. In other integration apps, there is a delay function that provides a timer that cancels itself if called multiple times. We can also find another way to improve this.

**Comment by provokateurin** [comment]
As per our discussion:

> Maybe the reference provider should only be registered if an API key is defined

Good idea, but we should keep it so an error message is shown when no API key is set (so we don't change anything here).

> The /models route is not used. Did you plan to make it possible to set the default used model in the admin settings? You could retrieve the list of available models as soon as an API key is defined and let the admin choose one which would be stored with the completion_model app config key.

It is used, but there is a bug in the frontend that can make it fail sometimes (I'll fix that).
